### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by xmichaelx** [maxdavidson/typescript-library-boilerplate#66]
Hello I had error:
```
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
```

after trying to debug my tests in VS Code 1.14.2 on Windows 10. I found this issue: https://github.com/Izhaki/Typescript-Jasmine-Istanbul-Boilerplate/issues/1 and made a similar change turning 
`"node_modules/.bin/jest"` into `"node_modules/jest/bin/jest.js"` in launch.json and debugging started to work. I'm leaving it here for future reference :)

I don't know if it's helpful, but I can create pull request with it if you want.

**Comment by maxdavidson** [comment]
Fixed in 003e0a70407ce72b5706bfaad1ee866ba9118afe
